-- @file: mart__delivery__unified_dcm_basis.sql
-- @layer: marts
-- @description: Unifies DCM and Basis delivery data into a single schema using UNION ALL.
--               Fields unique to one platform are filled with NULLs in the other to preserve schema alignment.
--               Enables cross-channel reporting and channel-comparison analytics.
-- @source: looker-studio-pro-452620.repo_tables.dcm
-- @source: looker-studio-pro-452620.repo_tables.basis
-- @target: looker-studio-pro-452620.repo_tables.delivery_unified

 create or replace table looker-studio-pro-452620.repo_tables.delivery_unified as

SELECT
  `impressions`,
  `clicks`,
  `utm_medium`,
  `media_cost`,
  `package_roadblock`,
  `utm_source`,
  `utm_content`,
  `date`,
  `campaign`,
  `utm_term`,
  `utm_campaign`,
  `prorated_planned_imps_pk`,
  `pkg_total_imps`,
  `max_flight_date`,
  `prorated_planned_cost_pk`,
  `p_package_friendly`,
  `p_pkg_daily_planned_cost`,
  `p_total_days`,
  `p_pkg_total_planned_imps`,
  `total_inflight_impressions`,
  `p_cost_method`,
  `package_id`,
  `placement_name`,
  `cpm_overdelivery_flag`,
  `placement_id`,
  `n_of_placements`,
  `d_max_date`,
  `p_end_date`,
  `p_pkg_daily_planned_imps`,
  `p_pkg_total_planned_cost`,
  `daily_recalculated_cost_flag`,
  `pkg_daily_imps`,
  `flight_date_flag`,
  `rate_raw`,
  `p_start_date`,
  `KEY` as dcm_key,
  `rich_media_video_completions`,
  `flight_status_flag`,
  `daily_recalculated_cost`,
  `min_flight_date`,
  `daily_cpm`,
  `p_advertiser_name`,
  `total_conversions`,
  `daily_recalculated_imps`,
  `creative`,
  `days_live`,
  `rich_media_video_plays`,
  `ad`,
  `pkg_daily_imps_perc`,
  `pkg_total_imps_perc`,
  `click_rate`,
  `utm_key`,
  `d_min_date`,
  `pkg_inflight_imps_perc`,
  `p_channel_group`,
  NULL AS `video_views`,
  NULL AS `creative_grouping`,
  NULL AS `n`,
  NULL AS `id`,
  NULL AS `gmail_dt`,
  NULL AS `url`,
  NULL AS `video_audio_plays`,
  NULL AS `meta_data_date_range`,
  NULL AS `video_audio_fully_played`,
  NULL AS `tactic`,
  NULL AS `meta_data_date_pull`,
  NULL AS `latest_record`,
  NULL AS `a_id`,
  NULL AS `creative_name`,
  NULL AS `placement`,
  NULL AS `key`,
  NULL AS `viewable_impressions`,
  NULL AS `basis_dsp_tactic_group`
FROM
  `looker-studio-pro-452620.repo_tables.dcm`
UNION ALL
SELECT
  `impressions`,
  `clicks`,
  `utm_medium`,
  `media_cost`,
  `package_roadblock`,
  `utm_source`,
  `utm_content`,
  `date`,
  `campaign`,
  `utm_term`,
  `utm_campaign`,
  NULL AS `prorated_planned_imps_pk`,
  NULL AS `pkg_total_imps`,
  NULL AS `max_flight_date`,
  NULL AS `prorated_planned_cost_pk`,
  NULL AS `p_package_friendly`,
  NULL AS `p_pkg_daily_planned_cost`,
  NULL AS `p_total_days`,

  NULL AS `p_pkg_total_planned_imps`,

  NULL AS `total_inflight_impressions`,
  NULL AS `p_cost_method`,
  NULL AS `package_id`,
  NULL AS `placement_name`,
  NULL AS `cpm_overdelivery_flag`,
  NULL AS `placement_id`,
  NULL AS `n_of_placements`,
  NULL AS `d_max_date`,
  NULL AS `p_end_date`,
  NULL AS `p_pkg_daily_planned_imps`,
  NULL AS `p_pkg_total_planned_cost`,
  NULL AS `daily_recalculated_cost_flag`,
  NULL AS `pkg_daily_imps`,
  NULL AS `flight_date_flag`,
  NULL AS `rate_raw`,
  NULL AS `p_start_date`,
  NULL AS `KEY`,
  NULL AS `rich_media_video_completions`,
  NULL AS `flight_status_flag`,
  NULL AS `daily_recalculated_cost`,
  NULL AS `min_flight_date`,
  NULL AS `daily_cpm`,
  NULL AS `p_advertiser_name`,
  NULL AS `total_conversions`,
  NULL AS `daily_recalculated_imps`,
  NULL AS `creative`,
  NULL AS `days_live`,
  NULL AS `rich_media_video_plays`,
  NULL AS `ad`,
  NULL AS `pkg_daily_imps_perc`,
  NULL AS `pkg_total_imps_perc`,
  NULL AS `click_rate`,
  NULL AS `utm_key`,
  NULL AS `d_min_date`,
  NULL AS `pkg_inflight_imps_perc`,
  NULL AS `p_channel_group`,
  `video_views`,
  `creative_grouping`,
  `n`,
  `id`,
  `gmail_dt`,
  `url`,
  `video_audio_plays`,
  `meta_data_date_range`,
  `video_audio_fully_played`,
  `tactic`,
  `meta_data_date_pull`,
  `latest_record`,
  `a_id`,
  `creative_name`,
  `placement`,
  `key` as basis_key,
  `viewable_impressions`,
  `basis_dsp_tactic_group`
FROM
  `looker-studio-pro-452620.repo_tables.basis`