CREATE
OR REPLACE TABLE giant-spoon-299605.tiktok_ads_tiktok_ads.tictok_ads_union_all AS
SELECT
    ad_group_id,
    ad_group_name,
    NULL AS ad_id,
    NULL AS ad_name,
    advertiser_id,
    advertiser_name,
    audience_type,
    NULL AS base_url,
    budget,
    campaign_id,
    campaign_name,
    category,
    clicks,
    comments,
    conversion,
    currency,
    daily_cpc,
    daily_cpm,
    daily_ctr,
    date_day,
    follows,
    gender,
    impressions,
    likes,
    profile_visits,
    reach,
    real_time_conversion,
    shares,
    source_relation,
    spend,
    total_conversion_value,
    total_purchase_value,
    total_sales_lead_value,
    NULL AS url_host,
    NULL AS url_path,
    NULL AS utm_campaign,
    NULL AS utm_content,
    NULL AS utm_medium,
    NULL AS utm_source,
    NULL AS utm_term,
    video_views_p_25,
    video_views_p_50,
    video_views_p_75,
    video_watched_2_s,
    video_watched_6_s
FROM
    `giant-spoon-299605.tiktok_ads_tiktok_ads.tiktok_ads__ad_group_report`
UNION ALL
SELECT
    ad_group_id,
    ad_group_name,
    ad_id,
    ad_name,
    advertiser_id,
    advertiser_name,
    audience_type,
    NULL AS base_url,
    budget,
    campaign_id,
    campaign_name,
    category,
    clicks,
    comments,
    conversion,
    currency,
    daily_cpc,
    daily_cpm,
    daily_ctr,
    date_day,
    follows,
    gender,
    impressions,
    likes,
    profile_visits,
    reach,
    real_time_conversion,
    shares,
    source_relation,
    spend,
    total_conversion_value,
    total_purchase_value,
    total_sales_lead_value,
    NULL AS url_host,
    NULL AS url_path,
    NULL AS utm_campaign,
    NULL AS utm_content,
    NULL AS utm_medium,
    NULL AS utm_source,
    NULL AS utm_term,
    video_views_p_25,
    video_views_p_50,
    video_views_p_75,
    video_watched_2_s,
    video_watched_6_s
FROM
    `giant-spoon-299605.tiktok_ads_tiktok_ads.tiktok_ads__ad_report`
UNION ALL
SELECT
    NULL AS ad_group_id,
    NULL AS ad_group_name,
    NULL AS ad_id,
    NULL AS ad_name,
    advertiser_id,
    advertiser_name,
    NULL AS audience_type,
    NULL AS base_url,
    NULL AS budget,
    NULL AS campaign_id,
    NULL AS campaign_name,
    NULL AS category,
    clicks,
    comments,
    conversion,
    currency,
    daily_cpc,
    daily_cpm,
    daily_ctr,
    date_day,
    follows,
    NULL AS gender,
    impressions,
    likes,
    profile_visits,
    reach,
    real_time_conversion,
    shares,
    source_relation,
    spend,
    total_conversion_value,
    total_purchase_value,
    total_sales_lead_value,
    NULL AS url_host,
    NULL AS url_path,
    NULL AS utm_campaign,
    NULL AS utm_content,
    NULL AS utm_medium,
    NULL AS utm_source,
    NULL AS utm_term,
    video_views_p_25,
    video_views_p_50,
    video_views_p_75,
    video_watched_2_s,
    video_watched_6_s
FROM
    `giant-spoon-299605.tiktok_ads_tiktok_ads.tiktok_ads__advertiser_report`
UNION ALL
SELECT
    NULL AS ad_group_id,
    NULL AS ad_group_name,
    NULL AS ad_id,
    NULL AS ad_name,
    advertiser_id,
    advertiser_name,
    NULL AS audience_type,
    NULL AS base_url,
    NULL AS budget,
    campaign_id,
    campaign_name,
    NULL AS category,
    clicks,
    comments,
    conversion,
    currency,
    daily_cpc,
    daily_cpm,
    daily_ctr,
    date_day,
    follows,
    NULL AS gender,
    impressions,
    likes,
    profile_visits,
    reach,
    real_time_conversion,
    shares,
    source_relation,
    spend,
    total_conversion_value,
    total_purchase_value,
    total_sales_lead_value,
    NULL AS url_host,
    NULL AS url_path,
    NULL AS utm_campaign,
    NULL AS utm_content,
    NULL AS utm_medium,
    NULL AS utm_source,
    NULL AS utm_term,
    video_views_p_25,
    video_views_p_50,
    video_views_p_75,
    video_watched_2_s,
    video_watched_6_s
FROM
    `giant-spoon-299605.tiktok_ads_tiktok_ads.tiktok_ads__campaign_report`
UNION ALL
SELECT
    ad_group_id,
    ad_group_name,
    ad_id,
    ad_name,
    advertiser_id,
    advertiser_name,
    audience_type,
    base_url,
    budget,
    campaign_id,
    campaign_name,
    category,
    clicks,
    comments,
    conversion,
    currency,
    daily_cpc,
    daily_cpm,
    daily_ctr,
    date_day,
    follows,
    gender,
    impressions,
    likes,
    profile_visits,
    reach,
    real_time_conversion,
    shares,
    source_relation,
    spend,
    total_conversion_value,
    total_purchase_value,
    total_sales_lead_value,
    url_host,
    url_path,
    utm_campaign,
    utm_content,
    utm_medium,
    utm_source,
    utm_term,
    video_views_p_25,
    video_views_p_50,
    video_views_p_75,
    video_watched_2_s,
    video_watched_6_s
FROM
    `giant-spoon-299605.tiktok_ads_tiktok_ads.tiktok_ads__url_report`