-- @file: mart__delivery__final_join_dcm_utms_prisma.sql
-- @layer: marts
-- @description: Final unified delivery model. Joins delivery data (DCM) with UTM enrichment
--               and Prisma metadata. Aligns placement and creative-level reporting with
--               campaign planning, actualized delivery, and cost model metrics.
-- @source: final_views.dcm
-- @source: final_views.utms_view
-- @source: final_views.prisma_view
-- @target: repo_tables.dcm
create or replace table `looker-studio-pro-452620.repo_tables.dcm` as

SELECT
  dcm.date,
  dcm.campaign,
  dcm.package_roadblock,
  dcm.package_id,
  dcm.placement_id,
  dcm.impressions,
  dcm.KEY,
  dcm.ad,
  dcm.click_rate,
  dcm.clicks,
  dcm.creative,
  dcm.media_cost,
  dcm.rich_media_video_completions,
  dcm.rich_media_video_plays,
  dcm.total_conversions,
  dcm.p_cost_method,
  dcm.p_package_friendly,
  dcm.p_start_date,
  dcm.p_end_date,
  dcm.p_total_days,
  dcm.p_pkg_daily_planned_cost,
  dcm.p_pkg_total_planned_cost,
  dcm.p_pkg_daily_planned_imps,
  dcm.p_pkg_total_planned_imps,
  dcm.p_channel_group,
  dcm.p_advertiser_name,
  dcm.flight_date_flag,
  dcm.flight_status_flag,
  dcm.rate_raw,
  dcm.n_of_placements,
  dcm.d_min_date,
  dcm.d_max_date,
  dcm.min_flight_date,
  dcm.max_flight_date,
  dcm.pkg_total_imps,
  dcm.total_inflight_impressions,
  dcm.pkg_daily_imps,
  dcm.pkg_daily_imps_perc,
  dcm.pkg_total_imps_perc,
  dcm.pkg_inflight_imps_perc,
  dcm.days_live,
  dcm.prorated_planned_cost_pk,
  dcm.prorated_planned_imps_pk,
  dcm.cpm_overdelivery_flag,
  dcm.daily_cpm,
  dcm.daily_recalculated_cost,
  dcm.daily_recalculated_cost_flag,
  dcm.daily_recalculated_imps,
  concat(dcm.placement_id, " || ", dcm.creative) as utm_key,
  utm.utm_source,
  utm.placement_name,
  utm.utm_campaign,
  utm.utm_medium,
  utm.utm_content,
  utm.utm_term,

  --prisma
    -- prisma_view.package_id,
    -- prisma_view.package_type,
    -- prisma_view.placement_type,
     prisma_view.placement_name as prsm_placement_name,
    -- prisma_view.start_date,
    -- prisma_view.end_date,
    -- prisma_view.cost_method,
    -- prisma_view.buy_type,
    -- prisma_view.buy_category,
    -- prisma_view.click_through_url,
    -- prisma_view.advertiser_name,
    -- prisma_view.campaign_name,
    -- prisma_view.supplier_code,
    -- prisma_view.supplier_name,
    -- prisma_view.planned_actions,
    -- prisma_view.planned_cost_pk,
    -- prisma_view.planned_clicks,
    -- prisma_view.advertiser_short_name,
    -- prisma_view.planned_imps_pk,
    -- prisma_view.planned_units,
    -- prisma_view.unit_type,
    -- prisma_view.dimension,
    -- prisma_view.media_name,
    -- prisma_view.product_code,
    -- prisma_view.product_name,
    -- prisma_view.external_entity_id,
    -- prisma_view.provider_name,
    -- prisma_view.package_group_name,
    -- prisma_view.out_of_home_end_date,
    -- prisma_view.placement_cap_cost,
    -- prisma_view.served_by,
     prisma_view.payable_rate as prsm_payable_rate,
    -- prisma_view.channel_if_buy_category,
    -- prisma_view.placement_type_site,
    -- prisma_view.device_type,
    -- prisma_view.audience_type,
    -- prisma_view.audience,
    -- prisma_view.initative,
    -- prisma_view.media_type,
    -- prisma_view.line_item_name,
    -- prisma_view.ad_size,
    -- prisma_view.funnel,
    -- prisma_view.kpi,
    -- prisma_view.geo_market,
    -- prisma_view.ad_server_placement_id,
    -- prisma_view.placement_number,
    -- prisma_view.placement_comments,
    -- prisma_view.days_in_out_of_home_end_date,
    -- prisma_view.package_name,
    -- prisma_view.placement_name2,
    -- prisma_view.report_date,
    -- prisma_view.script_run_date,
    -- prisma_view.channel,
    -- prisma_view.channel_raw,
    -- prisma_view.channel_group,
    -- prisma_view.campaign_friendly,
    -- prisma_view.p_package_friendly,
    -- prisma_view.n_of_placements,
    -- prisma_view.total_days,
    -- prisma_view.planned_daily_spend_pk,
    -- prisma_view.planned_daily_impressions_pk

FROM
  `looker-studio-pro-452620`.`final_views`.`dcm` AS dcm
left join looker-studio-pro-452620.final_views.utms_view as utm
on concat(dcm.placement_id, " || ", dcm.creative) = utm.placement_creative
left JOIN
  `looker-studio-pro-452620`.`final_views`.`prisma_view` AS prisma_view
ON
  dcm.package_id = prisma_view.package_id;